name: Scrape and Sum Table Numbers

on:
  push:
    paths:
      - 'scraper.py'
      - '.github/workflows/scrape_tables.yml'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper by 22f1001034@ds.study.iitm.ac.in
        run: python scraper.py
